### ISSUE TITLE
Batch size edit

### ISSUE THREAD

**Issue by Sarouch** [mikel-brostrom/yolo_tracking#1360]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, 
I am using the old version of this repo and I want to modify the batch size because of CUDA out of memory. Do you know where can I find the edit of the batch size to use track.py? 
this is the error:

`...
    result = self.forward(*input, **kwargs)
  File "C:\Users\chouchen2-admin\PycharmProjects\pythonProjecttest\YOLOV8\tracking_work\yolov8_tracking\trackers\strongsort\deep\models\resnet.py", line 149, in forward
    identity = self.downsample(x)
  File "C:\Users\user\anaconda3\envs\track_env\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\anaconda3\envs\track_env\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\user\anaconda3\envs\track_env\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\anaconda3\envs\track_env\lib\site-packages\torch\nn\modules\batchnorm.py", line 135, in forward
    return F.batch_norm(
  File "C:\Users\user\anaconda3\envs\track_env\lib\site-packages\torch\nn\functional.py", line 2149, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 1.95 GiB (GPU 0; 8.00 GiB total capacity; 5.07 GiB already allocated; 0 bytes free; 6.96 GiB reserved in total by PyTorch)`

**Comment by Sarouch** [comment]
> Use `--imgz` to lower the resolution of your images

Thank you, that works

**Comment by Sarouch** [comment]
Thank you, that works
